title: jet's blog 
email: hi@mail.0xa.xyz
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://blog.0xa.xyz # the base hostname & protocol for your site
author: jet

markdown: kramdown
mathjax: enabled
